repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black Code Formatting
        description: Black is the uncompromising Python code formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Imports Sort
        description: This hook sorts the import section to cluster similar imports
        files: \.py$
        require_serial: true
        types: [ python ]
        language: python
        entry: isort
        args: [ '--filter-files', '--length-sort', '--force-sort-within-sections' ]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: [ '--disable', 'MD033' ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py36-plus]
      - id: nbqa-isort
