[tool.poetry]
name = "pydataops"
version = "0.1.0"
description = "Test multiple Python data processing libraries"
authors = ["Gustavo Maia <vm.gustavo31@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7.12"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
